spring:
  application:
    name: core-api

  # INSIGHT: datasource: The object that manages database connections for your application.
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/smart_list
    username: smart_list_user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect